name: mopong
description: A Mobile Pong Game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.0.0
  flame_audio: ^1.0.0
  bonsoir: ^1.0.1+2
  logging: ^1.0.2
  network_info_plus: ^2.1.2
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/audio/
     - assets/images/
